# Generated by Django 5.2.2 on 2025-06-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("welcome", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
