# Generated by Django 5.2.2 on 2025-09-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("welcome", "0002_alter_user_email_alter_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(default="", max_length=100, unique=True),
        ),
    ]
