# Generated by Django 5.2.2 on 2025-09-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("welcome", "0003_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(default="", max_length=100),
        ),
    ]
