# Generated by Django 5.2.2 on 2025-09-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("welcome", "0004_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
