# Generated by Django 5.2.2 on 2025-09-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("welcome", "0005_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=100),
        ),
    ]
