# Generated by Django 5.2.2 on 2025-09-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("welcome", "0006_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
