# Generated by Django 5.2.2 on 2025-06-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="user_id",
            new_name="user",
        ),
    ]
