# Generated by Django 5.2.2 on 2025-06-22 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0002_rename_user_id_task_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="description",
        ),
    ]
