# Generated by Django 5.2.2 on 2025-09-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0003_remove_task_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
