# Generated by Django 5.2.2 on 2025-09-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0004_alter_task_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
