# Generated by Django 5.2.2 on 2025-09-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0005_alter_task_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
